### PR TITLE
Use MyProc->isBackgroundWorker to filter Background Workers

### PR DESCRIPTION
**Pull request by blogh**

### CODE REVIEW

**Comment by gleu** [comment]
This is interesting but there's one issue. I don't remember when PostgreSQL started to have background workers, but in 9.5, they were already there, even though isBackgroundWorker wasn't available at the time. I guess we should keep the old way for releases prior to 9.6, and use the new way for 9.6+. Care to fix this?

**Comment by gleu** [comment]
FWIW, this flag has been introduced with 13752743bf7 (PostgreSQL code). And we might have an issue with parallel queries.

**Comment by gleu** [comment]
9.3 is the first release with background workers.

**Comment by blogh** [comment]
>  Care to fix this?

will do.

**Comment by blogh** [comment]
Indeed there is a problem with parallel queries. We print one line per parallel worker.

**Comment by blogh** [comment]
On pgsql-12 without the patch.

The following :
```
psql <<EOF
CREATE TABLE toto(i int);
INSERT INTO toto(i) SELECT x FROM generate_series(1, 1000000) AS F(x);
SET parallel_setup_cost TO '0.0001';
SET parallel_tuple_cost TO '0.0001';
SELECT count(*) FROM toto;
DROP TABLE toto;
EOF
```

Logs :
```
INFO:  LOG_UQ statement: CREATE TABLE toto(i int);
CREATE TABLE
INFO:  LOG_UQ statement: INSERT INTO toto(i) SELECT x FROM generate_series(1, 1000000) AS F(x);
INSERT 0 1000000
INFO:  LOG_UQ statement: SET parallel_setup_cost TO '0.0001';
SET
SET
INFO:  LOG_UQ statement: SELECT count(*) FROM toto;
INFO:  LOG_UQ statement: SELECT count(*) FROM toto;
INFO:  LOG_UQ statement: SELECT count(*) FROM toto;
  count  
---------
 1000000
(1 row)

INFO:  LOG_UQ statement: DROP TABLE toto;
DROP TABLE
```

With the patch :
```
INFO:  LOG_UQ statement: CREATE TABLE toto(i int);
CREATE TABLE
INFO:  LOG_UQ statement: INSERT INTO toto(i) SELECT x FROM generate_series(1, 1000000) AS F(x);
INSERT 0 1000000
INFO:  LOG_UQ statement: SET parallel_setup_cost TO '0.0001';
SET
SET
INFO:  LOG_UQ statement: SELECT count(*) FROM toto;
  count  
---------
 1000000
(1 row)

INFO:  LOG_UQ statement: DROP TABLE toto;
DROP TABLE
```

So with the patch, parallel queries are logged correctly.
I do not understand yet why both SET are not logged.

NOTE: inverting the SET commands shows that only the first SET is logged.

**Comment by blogh** [comment]
I tried this:
```
static void                                                                     
pgluq_log(const char *query)                                                    
{                                                                               
        char *tmp_log_query = NULL;                                             
                                                                                
        elog(INFO, "Logger Start");                                             
        Assert(query != NULL);                                                  
                                                                                
        /* Check if the query have already been logged in the utility hook */   
        if (logged_in_utility_hook)                                             
        {                                                                       
                logged_in_utility_hook = false;                                 
                elog(INFO, "Logger Utility Hook");                              
                return;                                                         
        }                                                                       
        else                                                                    
                logged_in_utility_hook = false;                                 
                                                                                
                                                                                
        /* when log regexp statement is set do not log the query if it doesn't match the regexp */
        if ((log_query != NULL) && (regexec(&query_regexv, query, 0, 0, 0) != 0))
        {                                                                       
                elog(INFO, "Logger Filtered");                                       
                return;                                                         
        }                                                                       
                                                                                
        tmp_log_query = log_prefix(query);                                      
        if (tmp_log_query != NULL)                                              
        {                                                                       
                /*                                                              
                 * Write a message line to syslog or elog                       
                 * depending on the fact that we opened syslog at the beginning 
                 */                                                             
                if (openlog_done)                                               
                        write_syslog(syslog_level, tmp_log_query);              
                else                                                            
                        ereport(log_level, (errmsg("%s", tmp_log_query), errhidestmt(true)));
                                                                                
                /* Free the string */                                           
                pfree(tmp_log_query);                                           
        }                                                                       
        elog(INFO, "Logger End");                                               
} 
```

I get this for the two SET commands :
```
INFO:  Logger Start
INFO:  LOG_UQ statement: SET parallel_tuple_cost TO '0.0001';
INFO:  Logger End
SET
INFO:  Logger Start
INFO:  Logger Utility Hook
SET
```

It seems logged_in_utility_hook is still set to true when the second set is processed.

**Comment by blogh** [comment]
Reverting dae12e4724b44d0f356fb521ee9a47502e2dab64 seems to fix the problem.
I tested from 9.5 to 13.

**Comment by blogh** [comment]
tested from 9.0 to 9.4, it works that way. (all tests where done with the latest release)

**Pull request merged**
